### PR TITLE
react es5 -> es6

### PR DESCRIPTION
**Pull request by goldylucks**
Here's the [video companion](http://res.cloudinary.com/goldylucks/video/upload/v1486853729/nh_1_znrn7f.ogv)

### CODE REVIEW

**Comment by dondmcg** [comment]
Hey sorry npm start is not the way I run this project, when a change is made I stop the server and run 
$ webpack 

and then 

$ node server.js

**Comment by goldylucks** [comment]
gotcha

the convention is to put in the start script the main start command for the project, which is usually the webpack dev server.

then the server would go to a server script, so your package.json would look soemthing like this:

```js
...
"scripts": {
    "start": "webpack-dev-server",
  "server": "nodemon server"
}
...
```
notice I'm using webpack-sev-server instead of webpack, this will compile everything for the front end, listen to changes, AND serve the files.

[This tutorial](https://webpack.js.org/guides/hmr-react/) from the webpack team is great.

Also notice I'm using [nodemon](https://github.com/remy/nodemon) to restart the server automatically on changes

**Comment by dondmcg** [comment]
But when I tried to apply the edits I was getting an error from eslint that the files trying to import such as React are not present.  Will set up a time to go over.

**Comment by dondmcg** [comment]
I see your note about setting up the package json and using nodemon thanks for the tip.

**Comment by goldylucks** [comment]
>But when I tried to apply the edits

are you referring to the webpack tutorial?

When you post something, it's a good idea to post as much info as you can, screenshots if possible (Nimbus is a great extension for that)

**Pull request merged**
